### ISSUE TITLE
Image storage

### ISSUE THREAD

**Issue by joshday** [joshday/XKCD.jl#3]
<img width="508" alt="Screen Shot 2020-01-09 at 8 47 49 AM" src="https://user-images.githubusercontent.com/8075494/72072853-c3e49780-32bc-11ea-9da1-22c5cfee61fc.png">

**Comment by longemen3000** [comment]
maybe create an struct with custom printing?

**Comment by joshday** [comment]
I think Images is too heavyweight of a dependency for that, but if there’s an easier way I’d love to add it.

**Comment by longemen3000** [comment]
i was thinking more in the line of downloading the image when calling `comicdata()` and use a struct to store the JSON and the path to the downloaded image

**Comment by joshday** [comment]
<img width="632" alt="Screen Shot 2021-02-03 at 3 08 40 PM" src="https://user-images.githubusercontent.com/8075494/106803558-57100e00-6632-11eb-8fdb-c2050d91ef2a.png">
