### ISSUE TITLE
v.0.2.0 reverted?

### ISSUE THREAD

**Issue by gustaphe** [joshday/XKCD.jl#7]
It seems the version currently in the registry is v.0.1.0, despite having been v.0.2.0 at one point: https://github.com/JuliaRegistries/General/pull/29299

Was this an intentional reversion, or a registrator bug?

**Comment by joshday** [comment]
The latest release is `1.0.0`, not to be confused with `0.1.0`.  It looks like there must have been a TagBot issue since 1.0.0 isn't showing up as a release in this repo.

**Comment by joshday** [comment]
Hmm, on a manual run, TagBot failed to find a new release.  Looking into it...

**Comment by gustaphe** [comment]
Ah, yeah, I read that wrong. The real issue I was trying to debug is that `add XKCD` gave me `v"0.1.0"`. But that seems to be a compat clash, because doing it in a new environment gives `v"1.0.0"`. Off to figure out how to debug that.

**Comment by gustaphe** [comment]
My bottleneck was `DefaultApplication` which is limited to `0.1.0` here, but which has  a `1.0.0`, required for `PGFPlotsX`. Maybe you want to change the compat to `"< 2"`. The tests run fine, but I haven't looked into it a lot.

**Comment by joshday** [comment]
I removed upper bounds from compat and made a new a release.
